name: Update Economic Calendar Data
on:
  schedule:
    - cron: "0 9 * * *"  # Executa todo dia às 09:00 UTC (~06h BRT)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests playwright beautifulsoup4 python-dateutil pytz ics
          python -m playwright install --with-deps chromium

      - name: Run scraper
        run: python scripts/scrape_investing_calendar.py

      - name: Update README
        run: python scripts/update_readme.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/*.json data/*.ics README.md
          git commit -m "update data and readme" || echo "No changes to commit"
          git push
